### ISSUE TITLE
TypeError: cannot unpack non-iterable int object

### ISSUE THREAD

**Issue by metrob0y** [veebch/edify#12]
Hi!  Has anyone else come across this error when this script runs?   This error will point to line 111 amongst several other lines.   Nevertheless in this code of line it appears that there is a misplaced comma (,).   The line is written as follows:

text_width, = font.getbbox(text)[2]                     NOTE THE , AFTER WIDTH

Should this line in fact be:

text_width = font.getbbox(text)[2]                      SANS COMMA

This script runs now without the comma on line 111.    

This probably sounds like a stupid question to some of you veteran Python experts but this would be very helpful to me who does not know this language.   

This is a really cool raspberry Pi application that I find entertaining and practical to use.   I'm very thankful to the authors who built this as it inspires me to learn far more about rPi and Python.    Thank you kindly and thank you for your audience to my question.....

Tim

**Comment by veebch** [comment]
Thank you! This was just a typo left over from some tweaking because of depreciation in pillow. Fixed now!
