### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by battysakis** [veebch/edify#13]
Hello,

I had this up and running last year but my pi took a dump.  I tried installing following the instructions on the Git Hub and am running into the following error....  Any help would be appreciated!  Thanks!  Nick.

pi@raspberrypi:~/edify $ python3 edify.py

Traceback (most recent call last):
  File "/home/pi/edify/edify.py", line 41, in <module>
    import pandas as pd
  File "/home/pi/.local/lib/python3.9/site-packages/pandas/__init__.py", line 19, in <module>
    raise ImportError(
ImportError: Unable to import required dependencies:
numpy: Error importing numpy: you should not try to import numpy from
        its source directory; please exit the numpy source tree, and relaunch
        your python interpreter from there.
pi@raspberrypi:~/edify $

**Comment by veebch** [comment]
I ran into the same error and it had me baffled. I *think* the way I got round it was to uninstall numpy using pip and then reinstall it using apt-get.

The commands would be:
python3 -m pip uninstall numpy
sudo apt-get install python3-numpy

Give that a whirl and let me know if it works.....

**Comment by battysakis** [comment]
Hello,

Thank you for the response.  Unfortunately still seeing the same error.

At the step "python3 -m pip install -r requirements.txt" I was getting the following warning.  Perhaps that could be part of it?

WARNING: The script f2py is installed in '/home/pi/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

Screenshot
![Screenshot 2024-02-11 9 54 54 AM](https://github.com/veebch/edify/assets/99562505/899c719c-58a2-42fd-b626-c2b6cc723f9c)

**Comment by veebch** [comment]
That is installing numpy via pip again. I think you need to remove the pip version. 
python3 -m pip uninstall numpy
:)

**Comment by veebch** [comment]
Closing for now
