### ISSUE TITLE
Numpy?

### ISSUE THREAD

**Issue by ScottTheHippy** [veebch/edify#14]
Howdy Veebch,  Having just conquered all my snags with btcticker (and thank you again) I'm looping back to edify here.  I've covered the same steps- username is "pi", started with a "Lite" OS build, installed the various packages, updated the lines 449 and 479 in epd2in7_V2.py per the Waveshare guidance, and NOW when I try to launch edify.py, I get the following error:

![Screen Shot 2024-02-21 at 10 24 46 PM](https://github.com/veebch/edify/assets/101391563/9fcab315-bacf-474a-aa41-6b36aaaa1f30)

Any ideas on what exactly this is on about?  Is this likely a pandas or numpy deal?  Cheers!

**Comment by veebch** [comment]
Almost there! 

I've removed pandas from the requirements file and placed it in the apt-get preamble. This *should* work.

**Comment by ScottTheHippy** [comment]
Howdy Veebch,  Welp.  It seems to be running but nothing is happening on the display.  I ran the Waveshare test to confirm I'm not looking at a screen problem, and it does all its usual perfunctory displaying.  I've done the edits to the epd2in7_V2.py file (changing the "48000" to "5808" on those two lines, per previous fixing).  Might something else be keeping the screen from rendering?  Here's what I get at the command line:

![Screen Shot 2024-02-23 at 12 38 21 AM](https://github.com/veebch/edify/assets/101391563/c3b117bb-a409-4ce7-a843-f267a8ce5663)

Thanks!

**Comment by ScottTheHippy** [comment]
Howdy Veebch, I needed to update the edify.py file to replace "epd2in7" with "epd2in7_V2" as was the case with the bullion project, and hey presto- all squared away.  Thanks again for making these fun things.  :)

**Comment by veebch** [comment]
Thanks for giving all 3 projects a proper testing! Appreciated!
