### ISSUE TITLE
Couple Hangups

### ISSUE THREAD

**Issue by battysakis** [veebch/edify#3]
- Hello,

Working on putting this on my Pi Zero.

- Can you clarify "cp config_example.yaml config.yaml" under the install and run section.  When I run in edify directory I get an error cp: cannot stat 'config_example.yaml': No such file or directory

- Second issue is that I am getting an error message on both of the following...
python3 -m pip install -r requirements.txt and python3 -m pip install -r requirements.txt
_Error is ERROR: Could not find a version that satisfies the requirement RPi==0.0.1
ERROR: No matching distribution found for RPi==0.0.1_

Thank you.
Nick

**Comment by veebch** [comment]
Hey...
Thanks for pointing these out.... I'll fix them now

**Comment by veebch** [comment]
Give it a whirl now :)

**Comment by veebch** [comment]
Pleasure! And thanks for pointing out the error, it makes it easier for everyone else trying to follow the instructions. I'll close this, but if you run into any other roadblocks, raise another issue.
