### ISSUE TITLE
Auto Load

### ISSUE THREAD

**Issue by battysakis** [veebch/edify#6]
Hello,

I'm trying to understand how the script is running automatically at boot without me doing the "auto start" section.  This being a headless unit that is OK, but I am trying to teach myself some code with the screen when not being used as my Quote Bot.

I checked all [these](https://www.dexterindustries.com/howto/run-a-program-on-your-raspberry-pi-at-startup/) options for scripts loading automatically at boot but none are set up with edify.py.  

Also will not let me "PKILL" the edify.py script without it instantly starting again.

Thanks in Advance, Nick

**Comment by veebch** [comment]
It's because systemd is running it, and when it sees it die, it just starts it again.

`sudo systemctl stop edify.service` will stop it until the next reboot
